openapi: 3.0.0
info:
  title: 海外副業サイト
  description: This is a Global Job Site.
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: /
servers:
  - url: http://127.0.0.1:8000/
tags:
  - name: user
    description: Operations about user
  - name: job
    description: Everything about your Jobs
    externalDocs:
      description: Find out more
      url: http://127.0.0.1:8000/
paths:
  /api/user:
    get:
      tags:
        - user
      summary: Get user by user ID
      responses:
        '200':
          description: Get uccessfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 10
                email: test@example.com
                name: testuser
                status:
                  id: 1
                  name: 無料
                tag:
                  - id: 1
                    name: Nuxt.js
                  - id: 2
                    name: Vue.js
                match:
                  - id: 1
                    title: フロントエンド開発者募集
                    body: 現在フロントエンド開発者を募集しております。大規模開発の
                    published_at: 2023/7/10
                    image_url: http://job.company.example.com/job/1.jpg
                    price: ¥7,500,000/年
                    company:
                      id: 1
                      name: Job Ltd
                      address: アメリカ合衆国〇〇
                      country:
                        id: 1
                        name: アメリカ合衆国
                    category:
                      id: 1
                      name: フロントエンド開発
                    contract_type:
                      id: 1
                      name: 業務委託
                    tag:
                      - id: 1
                        name: Nuxt.js
                      - id: 2
                        name: Vue.js
                    remote:
                      id: 1
                      name: フルリモート
                  - id: 2
                    title: バックエンド開発者募集
                    body: 現在バックエンド開発者を募集しております。大規模開発の
                    published_at: 2023/7/10
                    image_url: http://job.company.example.com/job/2.jpg
                    price: ¥8,500,000/年
                    company:
                      id: 1
                      name: Job Ltd
                      address: アメリカ合衆国〇〇
                      country:
                        id: 1
                        name: アメリカ合衆国
                    category:
                      id: 2
                      name: バックエンド開発
                    contract_type:
                      id: 1
                      name: 業務委託
                    tag:
                      - id: 3
                        name: Go
                    remote:
                      id: 1
                      name: フルリモート
                
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              email: test@example.com
              password: '12345'
              name: testuser
              status_id: 1
              tag:
                - id: 1
                - id: 2
      responses:
        '200':
          description: Create successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Create successfully
    put:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      requestBody:
        description: Update an existing user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              email: test_updated@example.com
              password: '12345_updated'
              name: testuser_updated
              status_id: 1
              tag:
                - id: 1
                - id: 2
      responses:
        '200':
          description: Update successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Update successfully
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      responses:
        '200':
          description: Delete Succeed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Delete successfully
  /api/user/login:
    post:
      tags:
        - user
      summary: User login
      description: Login to the application
      requestBody:
        description: User credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              email: test@example.com
              password: '12345'
      responses:
        '200':
          description: Login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              example:
                token: your-auth-token
          headers:
            Set-Cookie:
              description: Authentication token
              schema:
                type: string
  /api/user/logout:
    post:
      tags:
        - user
      summary: User Logout
      description: Perform user logout
      responses:
        '200':
          description: Logout successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Logout successfully
  /api/job:
    get:
      tags:
        - job
      summary: Get all jobs
      description: Returns a list of all jobs
      parameters:
        - name: category_id
          in: query
          description: ID of the category to filter by
          required: false
          schema:
            type: integer
            format: int64
        - name: country_id
          in: query
          description: ID of the country to filter by
          required: false
          schema:
            type: integer
            format: int64
        - name: remote_id
          in: query
          description: ID of the remote to filter by
          required: false
          schema:
            type: integer
            format: int64
        - name: tag
          in: query
          description: List of tag IDs for filtering
          required: false
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
        - name: limit
          in: query
          description: Number of results per page (10 or 30)
          required: false
          schema:
            type: integer
            enum:
              - 10
              - 30
      responses:
        '200':
          description: Get successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
              example:
                - id: 1
                  title: フロントエンド開発者募集
                  body: 現在フロントエンド開発者を募集しております。大規模開発の
                  published_at: 2023/7/10
                  image_url: http://job.company.example.com/job/1.jpg
                  price: ¥7,500,000/年
                  company:
                    id: 1
                    name: Job Ltd
                    address: アメリカ合衆国〇〇
                    country:
                      id: 1
                      name: アメリカ合衆国
                  category:
                    id: 1
                    name: フロントエンド開発
                  contract_type:
                    id: 1
                    name: 業務委託
                  tag:
                    - id: 1
                      name: Nuxt.js
                    - id: 2
                      name: Vue.js
                  remote:
                    id: 1
                    name: フルリモート
                - id: 2
                  title: バックエンド開発者募集
                  body: 現在バックエンド開発者を募集しております。大規模開発の
                  published_at: 2023/7/10
                  image_url: http://job.company.example.com/job/2.jpg
                  price: ¥8,500,000/年
                  company:
                    id: 1
                    name: Job Ltd
                    address: アメリカ合衆国〇〇
                    country:
                      id: 1
                      name: アメリカ合衆国
                  category:
                    id: 2
                    name: バックエンド開発
                  contract_type:
                    id: 1
                    name: 業務委託
                  tag:
                    - id: 3
                      name: Go
                  remote:
                    id: 1
                    name: フルリモート
  /api/job/{jobId}:
    get:
      tags:
        - job
      summary: Get job by ID
      description: Returns a single job
      parameters:
        - name: jobId
          in: path
          description: ID of the job to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Get successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
              example:
                id: 1
                title: フロントエンド開発者募集
                body: 現在フロントエンド開発者募集を募集しております。大規模開発の...
                published_at: 2023/07/31
                price: ¥7,500,000/年
                company:
                  id: 1
                  name: Job Ltd
                  address: アメリカ合衆国
                  country:
                    id: 1
                    name: アメリカ合衆国
                category:
                  id: 1
                  name: フロントエンド開発
                contract_type:
                  id: 1
                  name: 業務委託
                tag:
                  - id: 1
                    name: Nuxt.js
                  - id: 2
                    name: Vue.js
                remote:
                  id: 1
                  name: フルリモート
                image_url: http://job.company.example.com/job/2.jpg
                url: http://job.company.example.com/job/100
                relate:
                  - id: 1
                    title: フロントエンド開発者募集
                    body: 現在フロントエンド開発者を募集しております。大規模開発の
                    published_at: 2023/7/10
                    image_url: http://job.company.example.com/job/1.jpg
                    price: ¥7,500,000/年
                    company:
                      id: 1
                      name: Job Ltd
                      address: アメリカ合衆国〇〇
                      country:
                        id: 1
                        name: アメリカ合衆国
                    category:
                      id: 1
                      name: フロントエンド開発
                    contract_type:
                      id: 1
                      name: 業務委託
                    tag:
                      - id: 1
                        name: Nuxt.js
                      - id: 2
                        name: Vue.js
                    remote:
                      id: 1
                      name: フルリモート
                  - id: 2
                    title: バックエンド開発者募集
                    body: 現在バックエンド開発者を募集しております。大規模開発の
                    published_at: 2023/7/10
                    image_url: http://job.company.example.com/job/2.jpg
                    price: ¥8,500,000/年
                    company:
                      id: 1
                      name: Job Ltd
                      address: アメリカ合衆国〇〇
                      country:
                        id: 1
                        name: アメリカ合衆国
                    category:
                      id: 2
                      name: バックエンド開発
                    contract_type:
                      id: 1
                      name: 業務委託
                    tag:
                      - id: 3
                        name: Go
                    remote:
                      id: 1
                      name: フルリモート
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
        name:
          type: string
        status:
          $ref: '#/components/schemas/UserStatus'
    UserTag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user:
          $ref: '#/components/schemas/User'
        tag:
          $ref: '#/components/schemas/Tag'
    UserStatus:
      type: object
      properties:
        id:
          type: integer
          format: int32
          enum:
            - 0
            - 1
            - 2
        name:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Job:
      type: object
      properties:
        id:
          type: integer
          format: int64
        site:
          $ref: '#/components/schemas/Site'
        url:
          type: string
        content:
          type: string
    HtmlTag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        job:
          $ref: '#/components/schemas/Job'
        title:
          type: string
        body:
          type: string
        language:
          $ref: '#/components/schemas/Language'
    Site:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        home_url:
          type: string
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        html_tag:
          $ref: '#/components/schemas/HtmlTag'
        title:
          type: string
        body:
          type: string
        Company:
          $ref: '#/components/schemas/Company'
        price:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        contact_type:
          $ref: '#/components/schemas/ContractType'
        remote:
          $ref: '#/components/schemas/Remote'
        published_at:
          type: string
          format: date
        image_url:
          type: string
        score:
          type: integer
          format: int64
    Language:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ItemTag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        item:
          $ref: '#/components/schemas/Item'
        tag:
          $ref: '#/components/schemas/Tag'
    Company:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ContractType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Remote:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  securitySchemes:
    user_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /auth
          scopes:
            write:user: modify your account
            read:user: read user
    api_key:
      type: apiKey
      name: api_key
      in: header